version: '3.9'

services:
  backendspring:
    image: roadmaps/roadmaps-backend-spring:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/roadmaps
       SPRING_DATASOURCE_USERNAME: postgres
       SPRING_DATASOURCE_PASSWORD: 12345
       SPRING_PROFILES_ACTIVE: dev

  frontendvaadin:
    image: roadmaps/roadmaps-frontend-vaadin:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "roadmaps"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command:
       - start-dev
    environment:
      KC_HTTP_PORT: 8085
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DATABASE: postgres
      KC_STORAGE: jpa
      KC_DB_URL: jdbc:postgresql://postgres:5432/roadmaps
      KC_DB_PASSWORD: 12345
      KC_DB_USERNAME: postgres
    ports:
       - "8085:8085"

volumes:
  postgres-data:
