version: '3.9'

services:
  backendspring:
    image: roadmaps/roadmaps-backend-spring:0.0.1-SNAPSHOT
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backendspring.rule=Host(`api.roadmaps-nikval.ru`)"
      - "traefik.http.routers.backendspring.tls=true"
      - "traefik.http.routers.backendspring.tls.certresolver=mytlschallenge"
    networks:
      - proxy-intranet

  frontendvaadin:
    image: roadmaps/roadmaps-frontend-vaadin:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontendvaadin.rule=Host(`roadmaps-nikval.ru`)"
      - "traefik.http.routers.frontendvaadin.tls=true"
      - "traefik.http.routers.frontendvaadin.tls.certresolver=mytlschallenge"
    networks:
      - proxy-intranet

networks:
  proxy-intranet:
    external:
      name: intranet
