version: '3.9'

services:
  backendspring:
    image: roadmaps/roadmaps-backend-spring:0.0.1-SNAPSHOT
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: dev

  frontendvaadin:
    image: roadmaps/roadmaps-frontend-vaadin:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: dev

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "roadmaps"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: