version: '3.7'

services:
  minio:
    image: bitnami/minio:2024.7.26
    container_name: minio
    restart: unless-stopped
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: miniodevelop
      MINIO_ROOT_PASSWORD: miniodevelop
      MINIO_CONSOLE_PORT_NUMBER: 9001
      MINIO_SERVER_URL: https://minio.roadmaps-nikval.ru
      MINIO_BROWSER_REDIRECT_URL: https://minio-client.roadmaps-nikval.ru/minio/ui
      MINIO_DEFAULT_BUCKETS: senderbucket, roadmapbucket
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.rule=Host(`minio.roadmaps-nikval.ru`)"
      - "traefik.http.routers.minio.tls=true"
      - "traefik.http.routers.minio.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.minio.service=minio@docker"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"

      - "traefik.http.routers.minio_client.entrypoints=websecure"
      - "traefik.http.routers.minio_client.rule=Host(`minio-client.roadmaps-nikval.ru`)"
      - "traefik.http.routers.minio_client.tls=true"
      - "traefik.http.routers.minio_client.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.minio_client.service=minio@docker"
      - "traefik.http.services.minio_client.loadbalancer.server.port=9001"
    volumes:
      - minio:/data

volumes:
  minio: