server:
  servlet:
    context-path: /api/v1/roadmaps
  port: ${BACKEND_PORT:8083}

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/roadmaps}
    username: ${DB_USERNAME:roadmaps}
    password: ${DB_PASSWORD:roadmaps}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URL:https://sso.roadmaps-nikval.ru/realms/roadmaps}

management:
  endpoints:
    web:
      exposure:
        include: "*"