spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres/roadmaps
    username: postgres
    password: 12345
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak/realms/roadmaps