spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://0.0.0.0:5432/roadmaps
    username: postgres
    password: 12345
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.roadmaps-nikval.ru/realms/roadmaps