server:
  servlet:
    context-path: /api/v1/roadmaps
  port: 8083

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/roadmaps
    username: postgres
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.roadmaps-nikval.ru/realms/roadmaps

management:
  endpoints:
    web:
      exposure:
        include: "*"