version: '3.9'

services:
  backendspring:
    image: roadmaps/roadmaps-backend-spring:0.0.1-SNAPSHOT
    ports:
      - "8083:8085"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend_prod.rule=Host(`prod-api.roadmaps-nikval.ru`)"
      - "traefik.http.routers.backend_prod.tls=true"
      - "traefik.http.routers.backend_prod.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.backend_prod.service=backend_prod@docker"
      - "traefik.htpp.services.backend_prod.loadbalancer.server.port=8083"

  frontendvaadin:
    image: roadmaps/roadmaps-frontend-vaadin:0.0.1-SNAPSHOT
    ports:
      - "8082:8084"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend_prod.rule=Host(`roadmaps-nikval.ru`)"
      - "traefik.http.routers.frontend_prod.tls=true"
      - "traefik.http.routers.frontend_prod.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.frontend_prod.service=frontend_prod@docker"
      - "traefik.htpp.services.frontend_prod.loadbalancer.server.port=8082"

