server:
  port: 8082

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  mustache:
    check-template-location: false
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URI:http://localhost:8080/realms/roadmaps}
      client:
        provider:
          keycloak:
            issuer-uri: ${KC_ISSUER_URI:http://localhost:8080/realms/roadmaps}
        registration:
          keycloak:
            client-secret: ${KC_CLIENT_SECRET:brqT8WCBezxJVikl7StgzaFY89wcSNA2}
            client-id: ${KC_CLIENT_ID:frontend-vaadin}
            scope: ${KC_SCOPE:profile,openid,email,roles}

vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.nikitin.roadmaps,org.bwajtr.ssokitdemo
  sso:
    login-route: /oauth2/authorization/keycloak
    back-channel-logout: true

backend:
  url: ${BACKEND_URL:http://localhost:8081/api/v1/roadmaps}

management:
  endpoints:
    web:
      exposure:
        include: "*"
