server:
  port: 8082

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  mustache:
    check-template-location: false
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8080/realms/roadmaps
      client:
        provider:
          keycloak:
            issuer-uri: https://localhost:8080/realms/roadmaps
        registration:
          keycloak:
            client-secret: ojwa2aHY0wjXI1Q2X1SyEZfnEFeshQBM
            client-id: frontend-vaadin
            scope: profile,openid,email,roles

vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.nikitin.roadmaps,org.bwajtr.ssokitdemo
  sso:
    login-route: /oauth2/authorization/keycloak
    back-channel-logout: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
