version: '3.9'

services:
  configserver:
    image: roadmaps/roadmaps-config-server:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    networks:
      backend:
        aliases:
          - "config-server"

  eurekaserver:
    image: roadmaps/roadmaps-eureka-server:0.0.1-SNAPSHOT
    ports:
      - "8083:8083"
    depends_on:
      - configserver
    networks:
      backend:
        aliases:
          - "eureka-server"

  gatewayserver:
    image: roadmaps/roadmaps-gateway-server:0.0.1-SNAPSHOT
    ports:
      - "8084:8084"
    depends_on:
      - configserver
      - eurekaserver
    networks:
      backend:
        aliases:
          - "gateway-server"

  backendspring:
    image: roadmaps/roadmaps-backend-spring:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    depends_on:
      - configserver
      - eurekaserver
      - gatewayserver
    networks:
      backend:
        aliases:
          - "backend-spring"

  frontendvaadin:
    image: roadmaps/roadmaps-frontend-vaadin:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - configserver
      - eurekaserver
      - gatewayserver
      - backendspring
    networks:
      backend:
        aliases:
          - "frontend-vaadin"

  keycloak:
    image: jboss/keycloak
    environment:
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8085:8085"
    depends_on:
      - keycloak-postgres
    networks:
      backend:
        aliases:
          - "keycloak"

  keycloak-postgres:
    image: library/postgres:-14
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -d postgres
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  backend:
    driver: bridge