version: '3.9'

services:
  configserver:
    image: roadmaps/roadmaps-config-server:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    networks:
      backend:
        aliases:
          - "config-server"

  eurekaserver:
    image: roadmaps/roadmaps-eureka-server:0.0.1-SNAPSHOT
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - configserver
    networks:
      backend:
        aliases:
          - "eureka-server"

  gatewayserver:
    image: roadmaps/roadmaps-gateway-server:0.0.1-SNAPSHOT
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - configserver
      - eurekaserver
    networks:
      backend:
        aliases:
          - "gateway-server"

  backendspring:
    image: roadmaps/roadmaps-backend-spring:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - configserver
      - eurekaserver
      - gatewayserver
    networks:
      backend:
        aliases:
          - "backend-spring"

  frontendvaadin:
    image: roadmaps/roadmaps-frontend-vaadin:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - configserver
      - eurekaserver
      - gatewayserver
      - backendspring
    networks:
      backend:
        aliases:
          - "frontend-vaadin"

  postgreskeycloak:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_SCHEMA: keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command:
      - start-dev
    environment:
      KC_HTTP_PORT: 8085
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DATABASE: postgres
      KC_STORAGE: jpa
      KC_DB_URL: jdbc:postgresql://postgreskeycloak:5432/keycloak
      KC_DB_SCHEMA: public
      KC_DB_PASSWORD: keycloak
      KC_DB_USERNAME: keycloak
    ports:
      - "8085:8085"
    depends_on:
      - postgreskeycloak

networks:
  backend:
    driver: bridge
