server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/

spring:
  mustache:
    check-template-location: false
  jpa:
    defer-datasource-initialization: true

vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.nikitin.roadmaps

management:
  endpoints:
    web:
      exposure:
        include: "*"