server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  mustache:
    check-template-location: false
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8085/realms/roadmaps
        registration:
          keycloak:
            client-secret: XFiV7e9cXlCiy2Txh9UMJuAkt8dYXc19
            client-id: frontend-vaadin
            scope: profile,openid,email,roles

vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.nikitin.roadmaps,org.bwajtr.ssokitdemo
  sso:
    login-route: /oauth2/authorization/keycloak
    back-channel-logout: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

keycloak.client-id: frontend-vaadin
keycloak.client-secret: XFiV7e9cXlCiy2Txh9UMJuAkt8dYXc19
keycloak.scope: profile, email, roles
keycloak.authorization-grant-type: client_credentials

keycloak.authorization-uri: http://localhost:8085/realms/roadmaps/protocol/openid-connect/auth
keycloak.user-info-uri: http://localhost:8085/realms/roadmaps/protocol/openid-connect/userinfo
keycloak.token-uri: http://localhost:8085/realms/roadmaps/protocol/openid-connect/token
keycloak.logout: http://localhost:8085/realms/roadmaps/protocol/openid-connect/logout
keycloak.jwk-set-uri: http://localhost:8085/realms/roadmaps/protocol/openid-connect/certs
keycloak.certs-id: vpuC8EAeHUEUBBpX6hsjltddMsaJewPlucOctSVVuIM