server:
  port: 8084

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"