server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  mustache:
    check-template-location: false
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-secret: XFiV7e9cXlCiy2Txh9UMJuAkt8dYXc19
            issuer-uri: http://localhost:8085/realms/roadmaps
            client-id: frontend-vaadin
            scope: profile,openid,email,roles

vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.nikitin.roadmaps,org.bwajtr.ssokitdemo
  sso:
    login-route: /oauth2/authorization/roadmaps
    back-channel-logout: true

management:
  endpoints:
    web:
      exposure:
        include: "*"