server:
  port: ${FRONTEND_PORT:8082}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  mustache:
    check-template-location: false
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URI:https://www.roadmaps-nikval.ru/realms/roadmaps}
          refresh_token_uri: ${KC_REFRESH_TOKEN:https://www.roadmaps-nikval.ru/realms/roadmaps/protocol/openid-connect/token}
      client:
        provider:
          keycloak:
            issuer-uri: ${KC_ISSUER_URI:https://www.roadmaps-nikval.ru/realms/roadmaps}
        registration:
          keycloak:
            client-secret: ${KC_CLIENT_SECRET:ol4qNtBOPzZDMskHD6c8hKGYUqaeZuKM}
            client-id: ${KC_CLIENT_ID:dev-roadmaps}
            scope: ${KC_SCOPE:profile,openid,email,roles}

vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.nikitin.roadmaps,org.bwajtr.ssokitdemo
  sso:
    login-route: /oauth2/authorization/keycloak
    back-channel-logout: true

backend:
  url: ${BACKEND_URL:http://localhost:8083/api/v1/roadmaps}

management:
  endpoints:
    web:
      exposure:
        include: "*"