version: '3.9'

services:
  backendspring:
    image: roadmaps/roadmaps-backend-spring:0.0.1-SNAPSHOT
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      DB_USERNAME: ""
      DB_PASSWORD: ""
      KC_ISSUER_URL: "http://sso.roadmaps-nikval.ru/realms/roadmaps"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend_dev.rule=Host(`dev-api.roadmaps-nikval.ru`)"
      - "traefik.http.routers.backend_dev.tls=true"
      - "traefik.http.routers.backend_dev.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.backend_dev.service=backend_dev@docker"
      - "traefik.htpp.services.backend_dev.loadbalancer.server.port=8083"

  frontendvaadin:
    image: roadmaps/roadmap-frontend:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      KC_ISSUER_URI: "http://sso.roadmaps-nikval.ru/realms/roadmaps"
      KC_REFRESH_TOKEN: "http://sso.roadmaps-nikval.ru/realms/roadmaps/protocol/openid-connect/token"
      KC_CLIENT_SECRET: "IMD6I1A955fNxfJt5LXdOHWnI7x0PJBG"
      KC_CLIENT_ID: "dev-roadmaps"
      KC_SCOPE: "profile,openid,email,roles"
      BACKEND_URL: "http://dev-api.roadmaps-nikval.ru/api/v1/roadmaps"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend_dev.rule=Host(`dev.roadmaps-nikval.ru`)"
      - "traefik.http.routers.frontend_dev.tls=true"
      - "traefik.http.routers.frontend_dev.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.frontend_dev.service=frontend_dev@docker"
      - "traefik.http.services.frontend_dev.loadbalancer.server.port=8082"

