name: deploy

on:
  push:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: self-hosted
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.4

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: maven

      - name: run tests
        run: mvn test

  prepare-enviroment:
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v3

      - run: docker-compose down

      - run: docker system prune -a -f

  deploy:
    runs-on: self-hosted
    needs: prepare-enviroment
    steps:
      - uses: actions/checkout@v3

      - run: mvn clean package -Pproduction

      - run: mvn dockerfile:build

      - run: docker-compose up -d

