name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  BACKEND_IMAGE: hamelion/roadmaps-backend-spring
  FRONTEND_IMAGE: hamelion/roadmaps-frontend-vaadin

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend
        uses: docker/build-push-action@v3
        with:
          context: ./roadmaps-backend-spring
          file: ./roadmaps-backend-spring/Dockerfile
          push: true
          tags: ${{env.BACKEND_IMAGE}}
