name: maven

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: SETUP_JDK_17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Maven
      run: mvn compile

    - name: Test
      run: mvn test

    - name: Package
      run: mvn package
      
    - run: mkdir artifact && cp target/*.jar artifact

    - uses: actions/upload-artifact@v3
      with: 
        name: Package
        path: artifact
